- src/App.css
- src/App.js
- src/components/navbar/Navbar.js
- src/index.css
- src/index.js
Changed the background to be universally reflected on each page, added nav logo, and changed a couple of css stylings.
> Changed styling and added site logo

- src/App.js
- src/components/pages/BrowseStudents.js
this is to help test API calls for Firestore
> added a browse students page with list of student names

- src/App.css
- src/components/pages/Login.js
- src/components/pages/SignUp.js
Made the login button now visible and signup button reflects those changes too.
> Made signup/login buttons look better

- src/components/pages/SignUp.js
Just had to add the class for the signup button back
> Fixed signup button

- package-lock.json
- package.json
- public/index.html
- src/components/navbar/Navbar.js
- src/index.js
Got bootstrap to work on our project, as well as changed the navbar section to properly reflect this change.
> Implemented bootstrap into the project

- public/index.html
- src/App.css
- src/App.js
- src/components/navbar/Navbar.js
- src/components/pages/About.js
- src/components/pages/Contact.js
- src/components/pages/Home.js
- src/components/pages/Login.js
- src/components/pages/SignUp.js
- src/components/pages/StudentProfilePage.js
- src/index.css
For the most part, I just changed A LOT of styling, but also added some code in to reroute the sign up/login to a profile page. Apologies in advance for such a large PR.
> Tons of styling changes and rerouted to prof page

- src/components/pages/StudentProfilePage.js
Added the student profile page, it isn't fully styled yet, but it is more important to get the functionality out of the way first
> Added Student Profile Page

- src/App.css
- src/components/pages/RentalMap.js
- src/components/pages/StudentProfilePage.js
- src/components/pages/Survey.js
Having issues trying to implement changes upon entering certain fields being reflected
> Attempting to fix student profile changes

- src/App.css
- src/components/pages/Questions.js
- src/components/pages/Survey.js
Made options sit centered under the question
changed color of selected answers 
changed color of word Survey
> made styling changes to Survey page

- src/components/pages/Questions.js
- src/components/pages/StudentProfilePage.js
- src/components/pages/Survey.js
Removed the import on both the questions and survey files to eliminate redundancy
Added/removed fields to better reflect the data represented on the student profile page.
> Minor changes to profile page and question/survey

- firebase-emulators-testing/fireStoreRules
- firestore.indexes.json
- firestore.rules
- functions/.eslintrc.js
- functions/.gitignore
- functions/index.js
- functions/jest.config.js
- functions/jsconfig.json
- functions/package-lock.json
- functions/package.json
- functions/src/test.js
- package-lock.json
- package.json
- src/App.js
- src/Protected.js
- src/components/navbar/Navbar.js
- src/components/pages/AuthDetails.js
- src/components/pages/Match.js
- src/components/pages/StudentProfilePage.js
- src/firebase-config.js
- src/firebase.js
- src/firebase.test.js
- src/index.js
- src/services/appSlice.js
- src/services/appStore.js
- src/services/selectors.js
- storage.rules
> added matching page, made changes to the student profile direction, added redux-react-toolkit and fixed  issues with prior pull request"

- src/App.js
- src/components/navbar/Navbar.js
- src/components/pages/ParentProfilePage.js
Basic parent profile added
app.js : added the route for parent profile page
navbar.js: added temporary route to parent profile page through navbar
parentprofilepage.js: just the profile page written in jsx, no functionality yet
> Added parent profile page

- src/components/navbar/Navbar.js
- src/components/pages/ParentProfilePage.js
- src/components/pages/StudentProfilePage.js
StudentProfilePage.js: Added toggle to parent page
ParentProfilePage.js: Added toggle to student page
Navbar.js: Removed parent from navbar
> Added toggle button

- src/components/pages/SignUp.js
Just added a radio to switch between parent and student on the sign up page.
> Added radio to switch between parent and student

- src/components/pages/RentalMap.js
RentalMap.js: added input fields and used geocoder and geometry libraries to get radius functionality working
> radius functionality working

- src/App.css
- src/components/pages/BrowseStudents.js
- src/components/pages/ParentProfilePage.js
Just added list of students to the parent profile page, only shows names without selector option
> Added list of students onto the parent profile

- functions/index.js
- functions/package.json
- functions/src/matches.js
- src/components/pages/Match.js
- src/firebase-config.js
Prior, there was an issue in which due to the functionsEmulator not being called, the matches were not displaying on the deployed site. This will allow for the matches to display.
> fixing front- end error for showing the matches

- src/App.css
- src/components/pages/Home.js
- src/components/pages/ParentProfilePage.js
- src/components/pages/StudentProfilePage.js
App.cs - changed some styling to alter icons
ParentProfilePage.js - added field for student email
StudentProfilePage.js - added br tags to space out buttons
Home.js - changed routing of social icons to home page of respective social media
> Fixed button spacing on profile page, changed hover effect on icons, added field for parent

- src/components/pages/SignUp.js
SignUp.js- added alerts notifying user about input requirements
> password reqs

- src/components/navbar/Navbar.js
Really simple fix that prevents the user from accessing the match and map sections when not logged in
> Removed match and map from appearing when not log

- functions/package-lock.json
- jsconfig.json
- src/App.css
- src/components/Conversations.js
- src/components/Messages.js
- src/components/pages/Chat.js
- src/components/pages/Contact.js
- src/components/pages/Login.js
- src/components/pages/Match.js
- src/components/pages/SignUp.js
- src/services/appSlice.js
update chat to only show messages belonging to people chatting
> update login, signup, contact us style

- src/components/pages/SignUp.js
Added feature where upon clicking the option for parent, the information provided will be sent straight to the parent db instead
> Added functionality where signup switches

- src/components/pages/RentalMap.js
RentalMap.js: routes to hunter college shown from each location
> directions working

- src/App.css
- src/components/pages/Home.js
- src/components/pages/ParentProfilePage.js
App.cs - Made quite a bit of styling changes, mainly affecting the home page and justification (mostly) across the board
home.js - Just added a class to the home page text to reflect class changes
parentprofilepage,js - removed a potential blocker that made it where it affected rendering
> Made changes to home page and overall styling

- src/components/navbar/Navbar.js
- src/components/pages/RentalMap.js
RentalMap.js: fixed centering, request, and infoWindow issues
NavBar.js: removed Map page link
> Extraneous requests + centering issue

- src/App.css
- src/components/pages/ParentProfilePage.js
app.css - center aligned navbar text upon phone size
parentprofilepage.js - integrated PIN requirement for the parent
> Added PIN requirement to the parent profile page
